'use strict';

// Declare app level module which depends on views, and components
angular.module('myApp', [
  'ngRoute',
  'myApp.about',
  'myApp.playground',
  'myApp.battery',
  'myApp.megsong',
  'myApp.alabama',
  'myApp.nationwide',
  'myApp.agendas',
  'myApp.m4a',
  'myApp.cgle',
  'myApp.covid',
  'myApp.sansduoone',
  'myApp.shared',
  'myApp.earTraining',
  'myApp.home',
  'myApp.music',
  'myApp.programs',
  'myApp.eeg',
  'myApp.zfest',
  'myApp.contact',
  'myApp.ideas',
  'myApp.minimalismGuitar',
  'myApp.fleet',
  'myApp.asking',
  'myApp.wch',
  'myApp.planing',
  'myApp.unset',
  'myApp.sightreadchristmas',
  'myApp.thesis',
  'myApp.nimb',
  'myApp.epoch',
  'myApp.breaking',
  'myApp.epochView',
  'myApp.departure',
  'myApp.wildthings',
  'myApp.genMel',
  'myApp.genMelView',
  'myApp.genMelPaper',
  'myApp.genSon',
  'myApp.pan',
  'myApp.genSonView',
  'myApp.genSonPaper',
  'myApp.split',
  'myApp.splitView',
  'myApp.genMelPsy',
  'myApp.songCycle',
  'myApp.twoVoices',
  'myApp.songsAndInterludes',
  'myApp.reflections',
  'myApp.threenotes',
  'myApp.smallMusic',
  'myApp.softMusic',
  'myApp.softMusicView',
  'myApp.chugga',
  'myApp.chuggaView',
  'myApp.version'
]).
config(['$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
  $locationProvider.hashPrefix('!');

  $routeProvider.otherwise({redirectTo: '/home'});
}]);
